Clinical Automation System/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CAS_DAL;
using CAS_DAL.Repositories;
using Clinical_Automation_System.ViewModel;

namespace Clinical_Automation_System.Controllers
{
    public class AdminController : Controller
    {
        DoctorRepository doctorRepo;
        UserRepository userRepo;
        public AdminController()
        {
            doctorRepo = new DoctorRepository();
            userRepo = new UserRepository();
        }
        [HttpGet]
        public ActionResult Index()
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 1))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            IEnumerable<User> usr = userRepo.GetAll();
            return View(usr);
        }
        [HttpPost]
        public ActionResult Index(string textUserName)
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 1))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            IEnumerable<User>  usr = userRepo.GetByNameAll(textUserName);
            return View(usr);
        }

        [HttpGet]
        public ActionResult AddDoctor()
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 1))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            ViewBag.Specialization = doctorRepo.GetAllSpecialization().ToList();
            return View();
        }
        [HttpPost]
        public ActionResult AddDoctor(UserDoctorModel ud)
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 1))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            ud.users.RoleId = 2;
            ud.users.IsActive = true;
            int newid = userRepo.Add(ud.users);
            ud.doctors.UserId = newid;
            int newid2 = doctorRepo.Add(ud.doctors);
            if (newid > 0 && newid2 > 0)
                return RedirectToAction("Success");
            else
                return View();
        }

        public ActionResult Success()
        {
            return View();
        }

    }
}

Clinical Automation System/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CAS_DAL;
using CAS_DAL.Repositories;

namespace Clinical_Automation_System.Controllers
{
    public class DoctorController : Controller
    {
        AppointmentRepository appointmentRepository;
        MedicineRepository medicineRepository;
        MessageRepository messageRepository;
        UserRepository userRepository;


        public DoctorController()
        {
            appointmentRepository = new AppointmentRepository();
            medicineRepository = new MedicineRepository();
            messageRepository = new MessageRepository();
            userRepository = new UserRepository();
        }
        // GET: Doctor
        public ActionResult Index()
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 2))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            return RedirectToAction("ViewAppointment");
        }


        [HttpGet]
        public ActionResult ViewMedicines()
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 2))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            IEnumerable<Medicine> medicines = medicineRepository.GetMedicinesAllForPatientAndDoctor();
            return View(medicines);
        }

        [HttpPost]
        public ActionResult ViewMedicines(string textMediName)
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 2))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            IEnumerable<Medicine> medicines = medicineRepository.GetMedicinesAllForPatientAndDoctorByName(textMediName);
            return View(medicines);
        }

        [HttpGet]
        public ActionResult ViewAppointment()
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 2))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            IEnumerable<Appointment> appointments = appointmentRepository.SearchbyDoctorId((int)Session["UserId"]);
            return View(appointments);
        }

        [HttpPost]
        public ActionResult ViewAppointment(DateTime txtAppDate)
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 2))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            IEnumerable<Appointment> appointments = appointmentRepository.SearchbyDoctorAppDate(txtAppDate, (int)Session["UserId"]);
            return View(appointments);
        }

        [HttpGet]
        public ActionResult Message()
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 2))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            var appointments = appointmentRepository.SearchbyDoctorId((int)Session["UserId"]);
            ViewBag.Appointments = appointments;
            return View();
        }
        [HttpPost]
        public ActionResult Message(int id)
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 2))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            ViewBag.PatientId = id;
            ViewBag.DoctorName = userRepository.GetByIdName(id);
            IEnumerable<Message> messages = messageRepository.GetBySenderIdAndRecieverId((int)Session["UserId"], id);
            var appointments = appointmentRepository.SearchbyDoctorId((int)Session["UserId"]);
            ViewBag.Appointments = appointments;
            return View(messages);
        }

        [HttpPost]
        public ActionResult AddMessage(int id, string txtMessage)
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 2))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            Message message = new Message();
            message.SenderId = (int)Session["UserId"];
            message.MessageTime = DateTime.Now;
            message.RecieverId = id;
            message.Status = "Sent";
            message.Message1 = txtMessage;
            int res = messageRepository.Add(message);
            return RedirectToAction("Message");
        }

    }
}

Clinical Automation System/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CAS_DAL;
using CAS_DAL.Repositories;

namespace Clinical_Automation_System.Controllers
{
    public class PatientController : Controller
    {
        DoctorRepository doctorRepository;
        AppointmentRepository appointmentRepository;
        MedicineRepository medicineRepository;
        MessageRepository messageRepository;
        UserRepository userRepository;

        public PatientController()
        {
            doctorRepository = new DoctorRepository();
            appointmentRepository = new AppointmentRepository();
            medicineRepository = new MedicineRepository();
            messageRepository = new MessageRepository();
            userRepository = new UserRepository();
        }

        [HttpGet]
        public ActionResult Index()
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 3))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }

            IEnumerable<Doctor> doctorVM=doctorRepository.GetAll();
            return View(doctorVM);
        }

        [HttpPost]
        public ActionResult Index(string txtspname)
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 3))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            IEnumerable<Doctor> doctorVM = doctorRepository.Search(txtspname.ToLower());
            return View(doctorVM);
        }

        [HttpGet]
        public ActionResult ViewAppointment()
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 3))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            IEnumerable<Appointment> appointments=appointmentRepository.SearchbyPateintId((int)Session["UserId"]);
            return View(appointments);
        }

        [HttpPost]
        public ActionResult ViewAppointment(DateTime txtappdate)
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 3))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            IEnumerable<Appointment>appointments= appointmentRepository.SearchbyPateintAppDate(txtappdate, (int)Session["UserId"]);
            return View(appointments);
        }

        [HttpPost]
        public ActionResult AddAppointment(int id)
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 3))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            Appointment appointment = new Appointment();
            appointment.DoctorId = id;
            appointment.IsApprove = false;
            appointment.StartDateTime = DateTime.Now.AddDays(7);
            appointment.PatientId = (int)Session["UserId"];
            appointment.Status = "Queue";
            appointment.Details = "Will be Updated by FontOffice";
            int result = appointmentRepository.Add(appointment);
            if (result == 1)
            {
                return RedirectToAction("ViewAppointment");
            }
            else
                return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ViewMedicines()
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 3))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            IEnumerable<Medicine> medicines=medicineRepository.GetMedicinesAllForPatientAndDoctor();
            return View(medicines);
        }

        [HttpPost]
        public ActionResult ViewMedicines(string textMediName)
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 3))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            IEnumerable<Medicine> medicines=medicineRepository.GetMedicinesAllForPatientAndDoctorByName(textMediName);
            return View(medicines);
        }

        [HttpGet]
        public ActionResult Message()
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 3))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            var appointments = appointmentRepository.SearchbyPateintIdApproved((int)Session["UserId"]);              
            ViewBag.Appointments = appointments;
            return View();
        }
        [HttpPost]
        public ActionResult Message(int id)
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 3))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            ViewBag.DoctorId = id;
            ViewBag.DoctorName = userRepository.GetByIdName(id);
            IEnumerable<Message> messages = messageRepository.GetBySenderIdAndRecieverId((int)Session["UserId"],id);
            var appointments = appointmentRepository.SearchbyPateintIdApproved((int)Session["UserId"]);
            ViewBag.Appointments = appointments;
            return View(messages);
        }

        [HttpPost]
        public ActionResult AddMessage(int id,string txtMessage)
        {
            if ((int)Session["userid"] == 0 || !((int)Session["RoleId"] == 3))
            {
                return RedirectToRoute(new
                {
                    controller = "account",
                    action = "login",
                });
            }
            Message message = new Message();
            message.SenderId = (int)Session["UserId"];
            message.MessageTime = DateTime.Now;
            message.RecieverId = id;
            message.Status = "Sent";
            message.Message1 = txtMessage;
            int res = messageRepository.Add(message);
            return RedirectToAction("Message");
        }


    }
}

Clinical Automation System/Views/Shared/_AdminOptions.cshtml
<div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            @Html.ActionLink("View User", "Index", "Admin", null, new { @class = "nav-link" })
        </li>
        <li class="nav-item">
            @Html.ActionLink("Add Doctor", "AddDoctor", "Admin", null, new { @class = "nav-link" })
        </li>
    </ul>

    <form action="/Account/Logout" method="post" class="form-inline my-2 my-lg-0">
        <span class="nav-link text-light"> Hi @Session["Name"],</span>
        <a class="btn btn-info my-2 my-sm-0" href="/Account/EditUser">Edit Profile</a>
        <button class="btn btn-secondary ml-1 my-2 my-sm-0" type="submit">LogOut</button>
    </form>
</div>

Clinical Automation System/Views/Shared/_DoctorOptions.cshtml
<div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            @Html.ActionLink("View Appointment", "ViewAppointment", "Doctor", null, new { @class = "nav-link" })
        </li>
        <li class="nav-item active">
            @Html.ActionLink("Messaging", "Message", "Doctor", null, new { @class = "nav-link" })
        </li>
        <li class="nav-item active">
            @Html.ActionLink("View Medicine", "ViewMedicines", "Doctor", null, new { @class = "nav-link" })
        </li>



    </ul>

    <form action="/Account/Logout" method="post" class="form-inline my-2 my-lg-0">
        <span class="nav-link text-light"> Hi @Session["Name"],</span>
        <a class="btn btn-info my-2 my-sm-0" href="/Account/EditUser">Edit Profile</a>
        <button class="btn btn-secondary ml-1 my-2 my-sm-0" type="submit">LogOut</button>
    </form>
</div>

Clinical Automation System/Views/Shared/_FontofficeOptions.cshtml
<div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            @Html.ActionLink("Add Patient", "AddPatient", "FontOffice", null, new { @class = "nav-link" })
        </li>
        <li class="nav-item active">
            @Html.ActionLink("Book Appointment", "BookAppointment", "FontOffice", null, new { @class = "nav-link" })
        </li>
        <li class="nav-item active">
            @Html.ActionLink("View Appointment", "ViewAppointment", "FontOffice", null, new { @class = "nav-link" })
        </li>
        <li class="nav-item active">
            @Html.ActionLink("View Appointment By Patient", "ViewAppointmentByPatient", "FontOffice", null, new { @class = "nav-link" })
        </li>
    </ul>

    <form action="/Account/Logout" method="post" class="form-inline my-2 my-lg-0">
        <span class="nav-link text-light"> Hi @Session["Name"],</span>
        <a class="btn btn-info my-2 my-sm-0" href="/Account/EditUser">Edit Profile</a>
        <button class="btn btn-secondary ml-1 my-2 my-sm-0" type="submit">LogOut</button>
    </form>
</div>

Clinical Automation System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Alaska CAS</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="">Alaska - Clinical Automation System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        @{
            int roleid = 0;
            if (Session["RoleId"] != null)
            {
                roleid = (int)Session["RoleId"];
            }
        }

        @if (roleid == 1)
        {
            @Html.Partial("_AdminOptions")
        }
        else if (roleid == 2)
        {
            @Html.Partial("_DoctorOptions")
        }
        else if (roleid == 3)
        {
            @Html.Partial("_PatientOptions")
        }
        else if (roleid == 4)
        {
            @Html.Partial("_FontofficeOptions")
        }
        else if (roleid == 5)
        {
            @Html.Partial("_PharmacyOptions")
        }

     
    </nav>
        
     <div class="container">
        @RenderBody()

        <hr />
        <footer id="footer">
            <div class="row">
                <div class="col-lg-12">
                    <p>Made by <a href="https://akshitchandora.com">Kira</a>.</p>
                    <p>&copy; @DateTime.Now.Year - Alaska CAS</p>
                </div>
            </div>
        </footer>
        <footer>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

Clinical Automation System/Views/Shared/_PatientOptions.cshtml
<div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            @Html.ActionLink("Search Doctor", "Index", "Patient", null, new { @class = "nav-link" })
        </li>
        <li class="nav-item active">
            @Html.ActionLink("View Appointment", "ViewAppointment", "Patient", null, new { @class = "nav-link" })
        </li>
        <li class="nav-item active">
            @Html.ActionLink("Messaging", "Message", "Patient", null, new { @class = "nav-link" })
        </li>
        <li class="nav-item active">
            @Html.ActionLink("View Medicines", "ViewMedicines", "Patient", null, new { @class = "nav-link" })
        </li>



    </ul>

    <form action="/Account/Logout" method="post" class="form-inline my-2 my-lg-0">
        <span class="nav-link text-light"> Hi @Session["Name"],</span>
        <a class="btn btn-info my-2 my-sm-0" href="/Account/EditUser">Edit Profile</a>
        <button class="btn btn-secondary ml-1 my-2 my-sm-0" type="submit">LogOut</button>
    </form>
</div>

Clinical Automation System/Views/Shared/_PharmacyOptions.cshtml
<div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            @Html.ActionLink("View Medicine", "Index", "Pharmacy", null, new { @class = "nav-link" })
        </li>
        <li class="nav-item active">
            @Html.ActionLink("Create Medicine", "Create", "Pharmacy", null, new { @class = "nav-link" })
        </li>
    </ul>

    <form action="/Account/Logout" method="post" class="form-inline my-2 my-lg-0">
        <span class="nav-link text-light"> Hi @Session["Name"],</span>
        <a class="btn btn-info my-2 my-sm-0" href="/Account/EditUser">Edit Profile</a>
        <button class="btn btn-secondary ml-1 my-2 my-sm-0" type="submit">LogOut</button>
    </form>
</div>